### ISSUE TITLE
Windows ver?

### ISSUE THREAD

**Issue by Outi-s** [jakebian/snaptile#2]
Hello, not really an issue. The simplicity of this tiling app is brilliant.

Most of the tiling programs I have tried to use had to be customized and I'm not very proficient in coding and stuff.

Wanted to ask if it is possible for you to port this for Windows?

I didn't see a comment section.

Apologies if this is inappropriate.

**Comment by jakebian** [comment]
Hey, if I was a Windows user I'd want this for Windows too, unfortunately that's beyond the scope of this project. Thanks for the support!
