### ISSUE TITLE
Doesn't work with keys in column

### ISSUE THREAD

**Issue by rothgar** [jakebian/snaptile#4]
If I try to put a window along the entire left side of my monitor I should be able to push ctrl + alt + Q + Z. However when I push those keys the window just ends up in the Z quadrant.

It works fine for diagonal and horizontal key presses but not for vertical. I haven't dug into the code yet but wanted to file an issue to track the problem.

**Comment by jakebian** [comment]
Hmm, can you just make sure that there's nothing else bound to those keys? If you run the python script from the terminal are there errors logged?

**Comment by rothgar** [comment]
Sorry for the late reply. I didn't see any shortcut keys using what I mapped them too (looking at GNOME key bindings) but I'll have to see if something else may be trying to intercept those keys. Nothing happens when I push them without snaptile running.

I'll have to troubleshoot another time though because after a recent git pull the script fails to run for me.

```
python3 ./snaptile.py
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Traceback (most recent call last):
  File "./snaptile.py", line 35, in <module>
    disp, root, lastkey_state, posmap = global_inital_states()
  File "./snaptile.py", line 21, in global_inital_states
    displ = display.Display()
  File "/usr/lib/python3.5/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python3.5/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/lib/python3.5/site-packages/Xlib/protocol/display.py", line 84, in __init__
    name, host, displayno, screenno = connect.get_display(display)
  File "/usr/lib/python3.5/site-packages/Xlib/support/connect.py", line 72, in get_display
    return mod.get_display(display)
  File "/usr/lib/python3.5/site-packages/Xlib/support/unix_connect.py", line 61, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""
```
I'm using fedora 25 so I'm guessing there's something different with my python 3 modules.
I'll try to troubleshoot and report back next week.

**Comment by rothgar** [comment]
I'm going to close this as I haven't had time to look at it or look for a fix.
